trigger:
  - main

pool:
  vmImage: 'ubuntu-18.04'

stages:
  - stage: Build
    jobs:
      - job: BuildAPI
        steps:
         - checkout: self
         - task: DotNetCoreCLI@2
           inputs:
              command: 'build'
         - task: PublishPipelineArtifact@1
           inputs:
            targetPath: "$(System.DefaultWorkingDirectory)/publish_output"
            artifact: "drop"
            publishLocation: "pipeline"
  - stage: Deploy
    jobs:
      - job: Deploy
        steps:
        - checkout: self
        - script: |
            terraform init
            terraform plan
            terraform apply
        - task: DownloadPipelineArtifact@2
          inputs:
              buildType: "current"
              artifactName: "drop"
              targetPath: "$(System.DefaultWorkingDirectory)"
        - task: AzureRmWebAppDeployment@4
          inputs:
              ConnectionType: "AzureRM"
              azureSubscription: "42c403e8-bc13-46ed-9007-9ab9b1509824"
              appType: "webApp"
              WebAppName: "warOfHeroes"
              packageForLinux: "$(System.DefaultWorkingDirectory)/WarOfHeroesUserAPI.zip"